FROM golang:1.25-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS build

RUN apk --no-cache add --no-check-certificate ca-certificates \
    && update-ca-certificates

WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 go build -o /regex-labeler /src/cmd/regex-labeler

FROM scratch
COPY --from=build /regex-labeler /regex-labeler
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/regex-labeler"]
