FROM golang:1.22-alpine AS build

RUN apk --no-cache add --no-check-certificate ca-certificates \
    && update-ca-certificates

WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 go build -o /ic-assignment /src/cmd/ic-assignment

FROM scratch
COPY --from=build /ic-assignment /ic-assignment
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/ic-assignment"]
