FROM golang:1.22-alpine@sha256:1699c10032ca2582ec89a24a1312d986a3f094aed3d5c1147b19880afe40e052 AS build

RUN apk --no-cache add --no-check-certificate ca-certificates \
    && update-ca-certificates

WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 go build -o /ic-assignment /src/cmd/ic-assignment

FROM scratch
COPY --from=build /ic-assignment /ic-assignment
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/ic-assignment"]
