FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS build

RUN apk --no-cache add --no-check-certificate ca-certificates \
    && update-ca-certificates

WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 go build -o /ic-assignment /src/cmd/ic-assignment

FROM scratch
COPY --from=build /ic-assignment /ic-assignment
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/ic-assignment"]
