name: Assign issues

on:
  issues:
    types:
      - labeled
      - reopened
jobs:
  run:
    runs-on: ubuntu-latest
    name: label issues
    permissions:
      contents: read
      issues: write
    concurrency:
      group: mimir-${{ github.event.issue.id }}-${{ github.event.action }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3.3.0
    - name: label issues
      uses: grafana/issue-team-scheduler/regex-labeler@v0.1
      with:
        cfg-path: .github/label-issues-cfg.yml
        dry-run: false
        abort-if-already-assigned: true